### ISSUE TITLE
Debugging client code in an OSGi + GWT application using SDBG

### ISSUE THREAD

**Issue by Alicia-L** [sdbg/sdbg#103]
Hello. In my company we're developing a web application that uses Equinox OSGi and GWT. I was looking into ways to debug the client-side code and ran into SDBG. I followed the video tutorial in http://sdbg.github.io/ (small example with GWT but no OSGi) and it worked.
However, it doesn't seem to work with our application (OSGi + GWT): the application runs and works normally, breakpoints on the server side work (as expected), but **breakpoints on the client side do not work**.

I'm completely new to all this so I would really appreciate some help.

# Setup
## Versions
**Eclipse:** 4.3.2 (Kepler)
**Google Web Toolkit SDK:** 2.6.0
**SDBG:** 1.0.2.201501121038

## Debug configurations
![debug configurations](https://cloud.githubusercontent.com/assets/10558652/5773393/820bd67e-9d62-11e4-8b32-8d05dea99f1f.png)

## OSGi Framework
Here's the one for the OSGi Framework ("Viewer Framework"):
![osgi framework - arguments](https://cloud.githubusercontent.com/assets/10558652/5773406/a04b6ba4-9d62-11e4-85b0-043fdc2e1d48.png)

![osgi framework - common](https://cloud.githubusercontent.com/assets/10558652/5773413/b4808d02-9d62-11e4-83c1-99095c9426ac.png)

## GWT Web Application
The one for GWT Web Application ("Viewer (SuperDev)"):
![gwt - main](https://cloud.githubusercontent.com/assets/10558652/5773425/d36ff734-9d62-11e4-8a60-afc7d54acdc0.png)

![gwt - server](https://cloud.githubusercontent.com/assets/10558652/5773435/ef9821d4-9d62-11e4-9da2-257551d6a37e.png)

![gwt - gwt](https://cloud.githubusercontent.com/assets/10558652/5773437/f742810e-9d62-11e4-9231-c65cef846cab.png)

![gwt - app engine](https://cloud.githubusercontent.com/assets/10558652/5773441/009e0fc0-9d63-11e4-9498-2d8da7dd29dc.png)

![gwt - arguments](https://cloud.githubusercontent.com/assets/10558652/5773445/0420de0c-9d63-11e4-8107-1607b7a9e145.png)

![gwt - jre](https://cloud.githubusercontent.com/assets/10558652/5773449/0be44138-9d63-11e4-806a-472ddb81479f.png)

![gwt - common](https://cloud.githubusercontent.com/assets/10558652/5773460/19b65d78-9d63-11e4-8ff2-7624876d11b9.png)

## Chrome
And the one for Chrome ("Viewer (SuperDev) - Chrome"):

![chrome - main](https://cloud.githubusercontent.com/assets/10558652/5773707/be59ebae-9d65-11e4-9215-573d19969d84.png)

![chrome - common](https://cloud.githubusercontent.com/assets/10558652/5773708/bff603f8-9d65-11e4-8c81-21b09767885e.png)

## GWT 2.6.0 -> linker "xsiframe"
Since I'm using GWT 2.6.0, I added the following line to my module definition, `viewer/web/Viewer.gwt.xml`:

```xml
<add-linker name="xsiframe"/>
```

# Debugging

1. Debug > Viewer Framework (OSGi):
![debug - osgi](https://cloud.githubusercontent.com/assets/10558652/5773562/3daec64c-9d64-11e4-9080-28b22aaa4524.png)

2. Debug > Viewer (SuperDev) (GWT Web Application):
![debug - gwt](https://cloud.githubusercontent.com/assets/10558652/5773626/c105bf78-9d64-11e4-988f-e0d4b3224066.png)

I get a warning that the port 8888 is already in use (by the OSGi application):
![port in use](https://cloud.githubusercontent.com/assets/10558652/5773628/c74b776a-9d64-11e4-87d3-73d96d1115fa.png)
I choose "Yes" (launch anyway).

GWT Console output:
```
Running GPE launcher for GWT-2.6.x version.
Runing CodeServer with parameters: [-noprecompile, -port, 9876, -bindAddress, 127.0.0.1, viewer.web.Viewer]
workDir: C:\Users\Alicia-L\AppData\Local\Temp\gwt-codeserver-1840218060715462844.tmp
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Module setup completed in 1191 ms

The code server is ready.
Next, visit: http://127.0.0.1:9876/
Creating nocache file: D:\stash\viewer.web\war\viewer\viewer.nocache.js
To compile the module 'viewer' , visit:
 http://127.0.0.1:9876/recompile/viewer?_callback=cback&user.agent=safari,gecko1_8,ie8,ie9,ie10
```

3. Debug > Viewer (SuperDev) - Chrome

![debug - chrome](https://cloud.githubusercontent.com/assets/10558652/5773745/3362bd7c-9d66-11e4-986f-a4979cbc3b22.png)

Chrome opens:

![compiling viewer](https://cloud.githubusercontent.com/assets/10558652/5773747/38122830-9d66-11e4-976a-fa95b221ca17.png)

GWT Console output:
```
Compiling module viewer.web.Viewer
...
   Compiling 1 permutation
      Compiling permutation 0...
      Source Maps Enabled
   Compile of permutations succeeded
Linking into C:\Users\Alicia-L\AppData\Local\Temp\gwt-codeserver-1840218060715462844.tmp\viewer.web.Viewer\compile-2\war\viewer; Writing extras to C:\Users\Alicia-L\AppData\Local\Temp\gwt-codeserver-1840218060715462844.tmp\viewer.web.Viewer\compile-2\extras\viewer
   Link succeeded
   Compilation succeeded -- 31.283s
Compile completed in 31650 ms
[WARN] sent source map for module: viewer
```

Chrome Console output:
```
09:56:53,896 |-INFO Initializer.publish - Initialized log formatters.
09:56:54,114 |-FINE PlaceController.publish - goTo: activity.client.DefaultPlace@23
09:56:54,126 |-INFO PlaceManager.publish - Starting activity Intent:{action=action.GOTO, data=#repo}.
09:56:54,136 |-FINE PlaceController.publish - goTo: viewer.web.client.RepositoryPlace@22
09:56:54,153 |-INFO PlaceManager.publish - Starting activity Intent:{action=undefined, component=ComponentName:{class=viewer.web.client.RepoActivity}}.
09:56:54,175 |-INFO SystemRuntime.publish - New application activity.client.app.Application@30 made.
09:56:54,895 |-INFO ActivitiesManager.publish - Service CREATED: Binder:{Intent:{action=undefined, component=ComponentName:{class=session.client.SessionService}}}.
09:56:54,912 |-INFO ActivitiesManager.publish - Service STARTED: Binder:{Intent:{action=undefined, component=ComponentName:{class=session.client.SessionService}}}.
09:56:54,960 |-INFO SystemRuntime.publish - Started activity viewer.web.client.RepoActivity@32.
09:56:54,996 |-FINE SystemRuntime.publish - Performing resume of viewer.web.client.RepoActivity@32 finished=false
09:56:55,003 |-FINE SystemRuntime.publish - Resume activity.client.app.SystemRuntime$ActivityRecord@36e startedActivity: false, hideForNow=false, finished=false
09:56:55,015 |-FINE SystemRuntime.publish - Resuming viewer.web.client.RepoActivity@32 with isForward=false
09:56:55,020 |-INFO ActivitiesManager.publish - Activity RESUMED: Binder:{Intent:{action=undefined, component=ComponentName:{class=viewer.web.client.RepoActivity}}}.
09:56:55,232 |-INFO NotificationManager.publish - Logged in Anonymously
09:56:55,237 |-INFO ActivitiesManager.publish - Service CREATED: Binder:{Intent:{action=undefined, component=ComponentName:{class=channel.client.ChannelService}}}.
09:56:55,247 |-INFO ChannelService.publish - Connecting web socket to ws://127.0.0.1:8888/view/channel?5B30511F635596DB
09:56:55,290 |-INFO ActivitiesManager.publish - Service STARTED: Binder:{Intent:{action=undefined, component=ComponentName:{class=channel.client.ChannelService}}}.
09:56:56,008 |-INFO ConnectionManager.publish - Started channel keep-alive with 5000 ms delay.
```

Chrome is now showing the application, which works fine.
Breakpoints in the server-side code work.
Breakpoints in the client-side code **do not work**.

Any ideas?
Thanks so much!

**Comment by ivmarkov** [comment]
Where is your breakpoint put? 
(a) In a code which is executed in the onModuleLoad() handler, 
(b) or in a code which is executed on a JavaScript event later on, say, in on-click of a button or suchlike?

If (a), then you are hitting #104, which is a well-known problem that I have to finally fix somehow.

**Comment by Alicia-L** [comment]
I tried both (a) and (b) and neither work for me.

**Comment by ivmarkov** [comment]
This is getting difficult... usually a breakpoint not being hit means it is in the onModuleLoad() method.
A few additional things to check:
* Are you sure you are using the Chrome window which was opened by SDBG itself?  I sometimes have a regular browser session, from within a regular Chrome window and I forget it is not in debug mode.
* Do you have Chrome Devtools opened in the browser? This is suspending the Eclipse debugger, as shown in the video
* Are your breakpoints hit if you use chrome Devtools instead of SDBG?

**Comment by Alicia-L** [comment]
> Are you sure you are using the Chrome window which was opened by SDBG itself? I sometimes have a regular browser session, from within a regular Chrome window and I forget it is not in debug mode.

Yes, it's the one opened by SDBG.

> Do you have Chrome Devtools opened in the browser? This is suspending the Eclipse debugger, as shown in the video.

No, Chrome Devtools are closed.
If I open them I see the message
```
<devtools opened - debugger connection paused>
```

and if I close them I get
```
<debugger connection resumed>
```

just like in the video.
For me by default they're closed and the eclipse breakpoints don't work. If I open and close Chrome Devtools, the eclipse breakpoints still don't work.

> Are your breakpoints hit if you use chrome Devtools instead of SDBG?

Just to be sure, do you mean like this?
1. Debug OSGi framework, GWT application and Chrome launcher as described in my original question.
2. Open Chrome Devtools and navigate to code (which is accessible because of source maps).
3. Set a breakpoint.
4. Try to trigger the breakpoint.
Or do I need to run the application in a different way?
I tried what I just described and it works:

![chrome-debug](https://cloud.githubusercontent.com/assets/10558652/5776408/369b5e74-9d87-11e4-8b75-b6ba4df2c793.png)

This breakpoint does not work in eclipse with SDBG (with Chrome Devtools closed).

**Comment by ivmarkov** [comment]
If you opened Chrome Devtools in the very same Chrome window that was launched by SDBG and it did work, then it looks like a bug in SDBG.

By the way, what is the SDBG version you are running? I just fixed a similar bug < week ago, which was caused by a bad sourcemap of a javascript library which was used as a dependency.

If you are using SDBG < 1.0.2, please upgrade it.

If you are using SDBG 1.0.2, then perhaps, it is related to a peculiarity of GWT 2.6.0. Here's what you can do to help me out diagnosing it further:
* Go to Eclipse/Window/Preferences and open the General->Tracing page.
* Click "Enable tracing" and then form the list below expand the SDBG node and set everything to "true" (or at least the "breakpoints" and "sourcemaps" nodes)
* Restart Eclipse
* Re-establish your debugging sessions as you have described above
* Once in debugging, in Eclipse, set the breakpoint in the click handler you have screenshot-ed above
* Click the button which is supposed to execute the code and hit the breakpoint (which does not happen)
* End all debugging session and send me the generated trace file.

**Comment by Alicia-L** [comment]
I'm running 1.0.2.201501121038.
I will do what you describe and get back to you.

Thanks so much for your support (and really fast reaction time!), I really appreciate it! :)

**Comment by Alicia-L** [comment]
Sorry, how can I send you the file? I don't see how to do it.

**Comment by ivmarkov** [comment]
Yes, GitHub issues are very primitive. Usually, people just upload these somewhere and then put a link reference to the files here in a comment.
Maybe you can upload it on Dropbox. Or you can create a new message in the SDBG Forums, attach the files there and then reference the message from here.

**Comment by Alicia-L** [comment]
Here you go :)
https://www.dropbox.com/s/1lecit3zvfse9l0/trace.log?dl=0

**Comment by ivmarkov** [comment]
OK the last two lines in the tracefile do indicate, that the Java breakpoint IS translated to a JavaScript breakpoint:
| Worker-0 | 2015-01-16 14:21:03.764 | com.github.sdbg.debug.core | /breakpoints | com.github.sdbg.debug.core.util.Trace | trace | 45 | Breakpoint [viewer/web/client/tools/FitToPage.java,35,-1] ==> mapped to [viewer-0.js,108932,6] |
| Worker-0 | 2015-01-16 14:21:03.764 | com.github.sdbg.debug.core | /breakpoints | com.github.sdbg.debug.core.util.Trace | trace | 45 | Set breakpoint [viewer-0.js,108932] |

The question is, is line 108932 indeed the line where your onclick callback code starts?
Can you open viewer-0.js in Chrome Devtools, go to that line and tell me if it looks like your onclick code?

**Comment by branflake2267** [comment]
In the SDM code server config the `-launcherDir` will be needed to point to the war, so that the compiled output gets put into the container. Otherwise you won't see the application. GPE's got a SDM code server launcher on its way, so it can perform better with custom backends. I can't remember if this flag can be passed through the dev mode entry point, if not, a custom launch has to be setup with the args. Only two args are needed for the CodeServer entrypoint, the -launcherDir and module.

**Comment by Alicia-L** [comment]
### @ivmarkov 
> The question is, is line 108932 indeed the line where your onclick callback code starts?
Can you open viewer-0.js in Chrome Devtools, go to that line and tell me if it looks like your onclick code?

Yes, it does:

![js-breakpoint](https://cloud.githubusercontent.com/assets/10558652/5797298/5c144062-9fb7-11e4-8437-6920a0ff1c82.png)


### @branflake2267 
Thanks, I'll look into that.

**Comment by Alicia-L** [comment]
### @branflake2267 
> I can't remember if this flag can be passed through the dev mode entry point

If you mean passing this as an argument to `com.google.gwt.dev.DevMode`, it is not possible:
```
Unknown argument: -launcherDir
Google Web Toolkit 2.6.0
DevMode [-[no]startServer] [-port port-number | "auto"] [-whitelist whitelist-string] [-blacklist blacklist-string] [-logdir directory] [-logLevel level] [-gen dir] [-bindAddress host-name-or-address] [-codeServerPort port-number | "auto"] [-[no]superDevMode] [-server servletContainerLauncher[:args]] [-startupUrl url] [-war dir] [-deploy dir] [-extra dir] [-workDir dir] module[s] 

where 
  -[no]startServer   Starts a servlet container serving the directory specified by the -war flag. (defaults to OFF)
  -port              Specifies the TCP port for the embedded web server (defaults to 8888)
  -whitelist         Allows the user to browse URLs that match the specified regexes (comma or space separated)
  -blacklist         Prevents the user browsing URLs that match the specified regexes (comma or space separated)
  -logdir            Logs to a file in the given directory, as well as graphically
  -logLevel          The level of logging detail: ERROR, WARN, INFO, TRACE, DEBUG, SPAM, or ALL
  -gen               Debugging: causes normally-transient generated types to be saved in the specified directory
  -bindAddress       Specifies the bind address for the code server and web server (defaults to 127.0.0.1)
  -codeServerPort    Specifies the TCP port for the code server (defaults to 9997 for classic-devMode or 9876 for super-devMode)
  -[no]superDevMode  Runs Super Dev Mode instead of classic Development Mode. (defaults to OFF)
  -server            Specify a different embedded web server to run (must implement ServletContainerLauncher)
  -startupUrl        Automatically launches the specified URL
  -war               The directory into which deployable output files will be written (defaults to 'war')
  -deploy            The directory into which deployable but not servable output files will be written (defaults to 'WEB-INF/deploy' under the -war directory/jar, and may be the same as the -extra directory/jar)
  -extra             The directory into which extra files, not intended for deployment, will be written
  -workDir           The compiler's working directory for internal use (must be writeable; defaults to a system temp dir)
and 
  module[s]          Specifies the name(s) of the module(s) to host
```

> if not, a custom launch has to be setup with the args. Only two args are needed for the CodeServer entrypoint, the -launcherDir and module.

I spent quite some time trying to set this up and I think it's too cumbersome and difficult to maintain, since it means giving up the automatic source-roots management provided by the Google Plugin.

Please let me know if I misunderstood what you meant.

**Comment by ivmarkov** [comment]
It looks like you've put the breakpoint on the line with the onClick() method signature, rather than on the first statement inside the method? Can you put a few more breakpoints inside the method and let me know the outcome?

**Comment by ivmarkov** [comment]
BTW are you sure that the breakpoint in Chrome DevTools was hit when you clicked on the button? Could it be, that it was hit immediately on application startup? That would explain a lot of things...

**Comment by Alicia-L** [comment]
> It looks like you've put the breakpoint on the line with the onClick() method signature, rather than on the first statement inside the method? Can you put a few more breakpoints inside the method and let me know the outcome?

I had set it on the first line inside the method. This is how it looks like in eclipse:

![2015-01-19_13h51_31](https://cloud.githubusercontent.com/assets/10558652/5800814/d6abd746-9fe3-11e4-971c-bb496891e0ce.png)

Now I've set additional breakpoints, like this:

![2015-01-19_13h56_20](https://cloud.githubusercontent.com/assets/10558652/5800817/e3ded67a-9fe3-11e4-8713-9369c3ed0e6f.png)

Here's the resulting trace:
https://www.dropbox.com/s/j1o2enrz0mpjcko/trace.log?dl=0

> BTW are you sure that the breakpoint in Chrome DevTools was hit when you clicked on the button? Could it be, that it was hit immediately on application startup? That would explain a lot of things...

Yes, I can open DevTools and click around as much as I want and no breakpoint is activated until I select "Fit to page" as shown here:

![chrome-debug](https://cloud.githubusercontent.com/assets/10558652/5800829/09b844c6-9fe4-11e4-9bc5-e40be0635cb1.png)

Then the breakpoint is activated.

**Comment by ivmarkov** [comment]
I am really running out of ideas.... I can come up with only two things:
* Unless it is too much effort, I would suggest replicating your setup on a colleague's workstation. Then at least we'll know if it is somehow related to your machine...
* Try to run your app with a newer GWT release, i.e. GWT 2.7.0

Finally, if you can isolate your problem to a GWT project that you can send me over, I can run SDBG in debug mode over your project to see what really is going on...

**Comment by branflake2267** [comment]
In order to use -launcherDir, you'll have to create a java application launcher, add the laundherDir and module. Run the server and sdm code server in separate processes.

**Comment by Alicia-L** [comment]
### @ivmarkov 
Ok, I'll try this
> Try to run your app with a newer GWT release, i.e. GWT 2.7.0

or this
> Unless it is too much effort, I would suggest replicating your setup on a colleague's workstation. Then at least we'll know if it is somehow related to your machine...

I think this...
> if you can isolate your problem to a GWT project that you can send me over, I can run SDBG in debug mode over your project to see what really is going on...

...would require quite some effort, since I cannot send any proprietary code and I would have to create an example from scratch, with no guarantee that it will also have this problem. I realize that this would be the easiest solution for you, though... so if we cannot figure this out maybe I have to try that in the end.

### @branflake2267 
> In order to use -launcherDir, you'll have to create a java application launcher, add the launcherDir and module.

Yes, this is what I did, but my module has lots of dependencies it is quite some work to set this up so that all necessary modules and their entry points are found. I'm sure this is possible but it's harder to maintain than with the Google Plugin, which provides automatic source-roots management.

Btw, -launcherDir is not recognized by CodeServer in version 2.6.0:
(It is in 2.7, which I should install anyway according to ivmarkov's suggestion)
```
Unknown argument: -launcherDir
Google Web Toolkit 2.6.0
CodeServer [-[no]precompile] [-[no]compileTest] [-bindAddress address] [-port port] [-workDir dir] [-[no]allowMissingSrc] [-src dir] [-X[no]enforceStrictResources] [-sourceLevel [auto, 1.6, 1.7]] [module]

where 
  -[no]precompile               Precompile modules. (defaults to ON)
  -[no]compileTest              Exits after compiling the modules. The exit code will be 0 if the compile succeeded. (defaults to OFF)
  -bindAddress                  The ip address of the code server. Defaults to 127.0.0.1.
  -port                         The port where the code server will run.
  -workDir                      The root of the directory tree where the code server willwrite compiler output. If not supplied, a temporary directorywill be used.
  -[no]allowMissingSrc          Allows -src flags to reference missing directories. (defaults to OFF)
  -src                          A directory containing GWT source to be prepended to the classpath for compiling.
  -X[no]enforceStrictResources  EXPERIMENTAL: Avoid adding implicit dependencies on "client" and "public" for modules that don't define any dependencies. (defaults to OFF)
  -sourceLevel                  Specifies Java source level (defaults to auto:1.7)
and 
  module                        The GWT modules that the code server should compile. (Example: com.example.MyApp)
```

> In order to use -launcherDir, you'll have to create a java application launcher, add the laundherDir and module. Run the server and sdm code server in separate processes. Forgot, have to add the CodeServer as the entrypoint.

Since I'm new to this I'm not sure I've got you. How many launchers do I have in your scenario?
* Java application:

![2015-01-20_08h52_48](https://cloud.githubusercontent.com/assets/10558652/5813690/de51d3c6-a081-11e4-98d2-211ba0a7bc5d.png)

![2015-01-20_08h54_56](https://cloud.githubusercontent.com/assets/10558652/5813696/0af286dc-a082-11e4-88fc-b2ae6c58e598.png)

* OSGi framework?

* GWT web application? 

* Chrome launcher?

**Comment by branflake2267** [comment]
Yeah, I don't recommend using Super Dev Mode with 2.6.0. I see main issues with 2.6.0 are resources don't get copied on init, super dev mode is slower, initial compile time is longer. But I suspect you're familiar with that already. 

Debugging launcher options:
A. DevMode entrypoint launcher only. Web server and Code Server come together (no breakpoints).
B. DevMode entrypoint launcher and SDBG chrome launcher. Web Server, CodeServer and javascript debugger connection. (Has breakpoints).
C. WTP Runtime Server launcher and Java application CodeServer entrypoint. (no breakpoints)
D. WTP Runtime Server launcher, CodeServer entrypoint launcher and SDBG Chrome launcher or javascript debugger. (has breakpoints)

In any case to match classic DevMode it's going to take three systems, web server, sdm code server, and javascript debugger (browser connection). They can be configured in a multiple ways. The goal is to boil it down to one launch with three processes and folks can choose how they do this. I think the most optimal way is using WTP facets in Eclipse although this story is being built as a prototype now. 

Eclipse uses the OSGI framework, I don't recommend using this in the client applications and I've never used this method to configure a project. Are you configuring your project this way and could I see an example? The RCP plugin framework uses it but thats another story.

**Comment by Alicia-L** [comment]
Sorry @ivmarkov and @branflake2267, I am currently taken up with something else. I will come back to this issue as soon as possible.
Thanks!

**Comment by ivmarkov** [comment]
Assumed stale. Please reopen if still happening.
