### ISSUE TITLE
Breakpoints set in Module.onModuleLoad() do not trigger

### ISSUE THREAD

**Issue by ivmarkov** [sdbg/sdbg#104]
This is a known race condition in that while the browser does inform us that a script was parsed, _it continues executing the just-parsed script without waiting for us to load the sourcemap, set the breakpoints etc._

A way to fix it at least partially is to remember the sourcemaps & breakpoints set acrross browser page refreshes and re-use those the second time onModuleLoad() is called. 

The above would require checks for stale scripts/sourcemaps, perhaps, by using md5 hashsums.

TODO: Also check how Chrome DevTools is doing it.

**Comment by keinhaar** [comment]
Not really an issue, as most applications will have some interactivity.
The race condition is still there, and is also true for firefox, edge and chromium. So debugging onModuleLoad will be difficult.
