### ISSUE TITLE
Remove variable name suffix

### ISSUE THREAD

**Issue by rdwallis** [sdbg/sdbg#105]
As mentioned here: https://github.com/sdbg/sdbg/issues/6 SDM variables have predicable suffixes.

Submitting a PR for this issue shortly.

**Comment by ivmarkov** [comment]
Thanks a lot for taking the time and providing a solution here.
I have some comments directly in PR #106

* @skybrian, can you shed some light on how variable names, field names and method names are mangled in GWT? 
** I think they are having some sort of suffix ending up on _g$, but then I see two variations:
*** The more frequent one: just _NNN_g$ (NNN being a sequence of numeric characters)
*** But sometimes, also NNN_NNN_g$. Seems to be used for values in inner classes or suchlike
** Is it safe to remove these suffixes for the stack-trace and the variable names? Whey are those there in the first place? I guess some name clashes?
** Can you take a look at PR #106 as well, specifically at the regex pattern at the end?

**Comment by skybrian** [comment]
The field naming is done in JsIncrementalNamer [1]. This namer is used in Super Dev Mode only. Yes, the numbering is to avoid name clashes. However, the namer acts rather conservatively; it assumes all names are used globally when in fact there might not be a name clash locally.

At least in 2.7 when using Super Dev Mode, you can assume that _NNN_g$ indicates some kind of Java field. I don't know what's going on with the inner classes; perhaps that's a synthetic field needed internally?

I think it's okay to remove the suffix. If there's a name clash, the user will have to open each one and guess which is which. But then, the numbering wouldn't help them anyway.

[1] https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/js/JsIncrementalNamer.java

**Comment by ivmarkov** [comment]
@rdwallis - just to let you know that I haven't forgotten about this PR - I'm still evaluating variants how it should work, esp. based on the further input I received from @skybrian in #6.

For now, I feel relatively strongly that there MUST be a single-click button in the UI which converts between raw JavaScript names and demangled ones. For one, if you want to write a watch expression in the Expressions view, it is not really possible if you do not have the raw JavaScript names around. And given that we do not have field completion in the Expressions view, the Variables view for now is your only reference...

**Comment by rdwallis** [comment]
Ok makes sense.  I don't use expressions very much so I missed that use
case.

**Comment by ivmarkov** [comment]
See my comments in #102 and #6 - this is now done. There will be a BETA release, 1.0.3 shortly.

**Comment by ivmarkov** [comment]
The BETA (1.0.3) is now available in the (well-hidden) P2 BETA repo: http://sdbg.github.io/p2beta/
