### ISSUE TITLE
Cannot use -bindAddress to use a different ip from 127.0.0.0

### ISSUE THREAD

**Issue by confile** [sdbg/sdbg#108]
Debugging works fine if I use the standard configuration. If I use 

```
-bindAddress 192.168.178.26
```
In my super dev mode debug config and if I add

```
http://192.168.178.26:8888/TestSDBG.html
```
as source in the ``Launch Chrome`` config then the debugger does not start. 

Is it only working with 192.0.0.0?

**Comment by branflake2267** [comment]
Try this, -bindAddress 0.0.0.0, it will bind on all the nics

Have a good day,
Brandon Donnelson
+Follow Me <https://plus.google.com/u/0/111739836936169749229/posts>

**Comment by confile** [comment]
@branflake2267 Great thank you. This should be added to the documentation.

**Comment by branflake2267** [comment]
Now that I think about it, what entrypoint is that getting used with, I was thinking in context of DevMode, so I might be wrong.

**Comment by ivmarkov** [comment]
I'm not sure here - is this a problem related to SDBG, or is it somehow related to the GWT SuperDevMode plugin or to both?

**Comment by confile** [comment]
``-bindAddress``only works with 0.0.0.0 and SDBG plugin.

**Comment by ivmarkov** [comment]
What exactly do you mean by "the debugger does not start" when you say
"
as source in the Launch Chrome config then the debugger does not start.
"

* Chrome appears but cannot load the app
* Chrome does not appear at all
* Chrome appears, app tries to load, but does not succeed

BTW: Is it working with ChromeDevTools?

**Comment by confile** [comment]
ChromeDevTools is not working with -bindAddress 192.168.178.26 It is only working with -bindAddress 0.0.0.0 

I  think for that reason the issue is fixed.

**Comment by ivmarkov** [comment]
OK I will close the issue, as this is not a problem in SDBG, however @branflake2267 may still want to look what is going on in the GWT plugin.

**Comment by branflake2267** [comment]
This doesn't sound like a GPE issue yet.

**Comment by ivmarkov** [comment]
OK but what is it then? Neither SDBG not ChromeDevTools seem to work when a concrete IP is specified; at least this is what @confile reports...
