### ISSUE TITLE
Memory Leak on Large Project

### ISSUE THREAD

**Issue by seamusmac** [sdbg/sdbg#118]
As per discussion at https://groups.google.com/forum/#!topic/sdbg/yJobiG_hTzk

I think there is a memory leak in SDBG for very large projects. 
I have provided https://gist.github.com/seamusmac/58f8710d4e019eb96904 

When passing data over the websocket it exceeds the maximun buffer size:

eg: [83512:83668:0220/160425:ERROR:http_connection.cc(110)] Too large write data is pending: size=107461448, max_buffer_size=104857600

Is there a way to increase the max_buffer_size?

**Comment by ivmarkov** [comment]
I'm not convinced yet that you have found a memory leak in SDBG. Sure, it is the Web Socket thread of SDBG that is complaining, but it could be that some other thread has eaten up all the memory. Heap is a shared resource, so if somebody takes all the memory, all others suffer and the out of memory exception can appear in any thread, including innocent ones that only take a tiny bit more memory, but then even that tiny bit is unavailable.

You can try is to see how big really is that ArrayList in your error thread dump. If it is indeed 10s of 100s of MBs, then there is some issue.

_But most important_: I think you should take a _heap dump_, not a thread dump, as in your case the thread dump is not telling that much - I was expecting to see quite some other SDBG threads out there, but the only SDBG presence are the 3 SDBG daemon threads. E.g. no sign of the real debugger threads. 

A side topic:
"http_connection.cc" is probably a C++ file belonging to Chrome itself, and not really part of SDBG. The message printed in the Eclipse console comes from the Chrome browser output itself. 
Therefore, even if increasing max_buffer_size (whatever it is) was an option, this is not really the solution. What you see is probably a symptom, not the disease.
