### ISSUE TITLE
Mirror Repo Feature

### ISSUE THREAD

**Issue by branflake2267** [sdbg/sdbg#120]
Will I cause any problems if I mirror this as a download feature in another plugin install?

**Comment by branflake2267** [comment]
![screen shot 2015-05-02 at 11 44 33 am](https://cloud.githubusercontent.com/assets/1326504/7442298/a7047470-f0c0-11e4-9f9e-a27f346a18f8.png)

**Comment by branflake2267** [comment]
Closing. If there are any objections speak up.

**Comment by ivmarkov** [comment]
How do you refer to the SDBG feature from within your installation?
If you refer to the exact SDBG version, that might be a problem, because I do not keep old SDBG releases in my P2 repo.

**Comment by branflake2267** [comment]
I used maven to mirror your repository as it is currently and planned to update on any new changes. I'm not interested in archiving anything old. There aren't any hard coded dependencies. Although I just noticed I have to include SDBG in the build process now, got to fix that tonight, but thats a different issue.

**Comment by branflake2267** [comment]
@ivmarkov I sent you an invite to the repo. Here is the mirror config: https://github.com/gwt-eclipse-plugin/gwt-eclipse-plugin/blob/master/mirrors/pom.xml#L155
