### ISSUE TITLE
Build server

### ISSUE THREAD

**Issue by branflake2267** [sdbg/sdbg#124]
If you're interested the build server that is being used for the gwt plugin can be used to build this. 

Would you like to have build requests build?
Would you like to setup a build for deploying?

http://146.148.64.240:8080/

**Comment by ivmarkov** [comment]
Well, if you are offering, I would gladly take advantage of your build infrastructure. :)

What I would really appreciate is if you can setup an SDBG nightly build, which is:
* Executing "mvn install"
* After that publishing the build artefacts (= the P2 repository created during the build) somewhere

**Comment by branflake2267** [comment]
Sounds good, I can do that. I can publish the artifacts to a Cloud Storage bucket easily. I'll aim to do this tonight.

**Comment by branflake2267** [comment]
Can you provide me with a username that I can use in team city?

**Comment by ivmarkov** [comment]
Umm, how about simply "sdbg"?

**Comment by ivmarkov** [comment]
Or if you want it to be personalized, ivmarkov would do as well...

**Comment by branflake2267** [comment]
Just wanted to confirm which directory you'd like to have copied to nightly?

com.github.sdbg.releng.p2/target/repository?

**Comment by branflake2267** [comment]
http://146.148.64.240:8080/viewLog.html?buildId=238&buildTypeId=Sdbg_SdbgNightly&tab=buildLog - I need the build steps. I roughed them out. You try editing it if you like or I can modify...

**Comment by branflake2267** [comment]
Never mind I think it's a build server issue...

**Comment by branflake2267** [comment]
I didn't have much time tonight to investigate. But mvn install is broken at the moment, it wants a target file or directory configuration that doesn't exist. 

INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: com.github.sdbg:com.github.sdbg.debug.core:1.0.5.qualifier @ /Users/branflake2267/git/sdbg/com.github.sdbg.debug.core/pom.xml
[ERROR] Internal error: java.lang.RuntimeException: I/O error while reading "/Users/branflake2267/git/sdbg/com.github.sdbg.releng.targetplatform/com.github.sdbg.releng.targetplatform.target": /Users/branflake2267/git/sdbg/com.github.sdbg.releng.targetplatform/com.github.sdbg.releng.targetplatform.target (No such file or directory) -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: I/O error while reading "/Users/branflake2267/git/sdbg/com.github.sdbg.releng.targetplatform/com.github.sdbg.releng.targetplatform.target": /Users/branflake2267/git/sdbg/com.github.sdbg.releng.targetplatform/com.github.sdbg.releng.targetplatform.target (No such file or directory)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)

**Comment by ivmarkov** [comment]
Please try again. I think I fixed it.

**Comment by branflake2267** [comment]
Cool, nice job. Success. Thank you. 

http://storage.googleapis.com/sdbg/snapshot

![screen shot 2015-05-08 at 9 01 46 am](https://cloud.githubusercontent.com/assets/1326504/7540123/e68f755a-f560-11e4-9a04-41e7aafddf83.png)

**Comment by branflake2267** [comment]
FYI, tested the nightly with the gwt-plugin (gpe fork) and it works fine. I'll test it with the current gpe next. 
![screen shot 2015-05-08 at 12 33 09 pm](https://cloud.githubusercontent.com/assets/1326504/7544047/7de34dce-f57e-11e4-8093-487d1d698dc2.png)

**Comment by branflake2267** [comment]
Updated SDBG with GPE and worked fine for me.
