### ISSUE TITLE
Release 1.0.5?

### ISSUE THREAD

**Issue by branflake2267** [sdbg/sdbg#129]
I'm waiting to announce the repos and update site when 1.0.5 is downloadable. When do you think that will be ready?

**Comment by branflake2267** [comment]
Any possibility to push out 1.0.5 this week?

**Comment by ivmarkov** [comment]
Yes, I'll try to.

**Comment by ivmarkov** [comment]
I've pushed a new release (1.0.6) to the P2 BETA repo:
http://sdbg.github.io/p2beta/

It has everything 1.0.5 had, plus bug-fixes (hopefully) for #100 (finally!), #131 and #132 
Please let me know if you find something not quite right with it, as I plan to push it to official in the enxt hours/days

**Comment by branflake2267** [comment]
Wow, Nice job! :) :+1:  I'll check shortly.

**Comment by ivmarkov** [comment]
I've pushed 1.0.6 to the release repo now.
I tested it in Eclipse 4.4 and Eclipse 3.8 - no problems detected so far. I also use it for my daily debugging activities.

**Comment by branflake2267** [comment]
Nice job!

Have a good day,
Brandon Donnelson
+Follow Me <https://plus.google.com/u/0/111739836936169749229/posts>
