### ISSUE TITLE
Eclipse breakpoints do not trigger

### ISSUE THREAD

**Issue by frank82178** [sdbg/sdbg#130]
Hi,

I read through the forum and the issues and I have no clue why the eclipse breakpoints
do not work for me. 
I placed the Eclipse breakpoints in various code parts but nothing triggers. 
The breakpoints set directly in the Chrome Sourcemap files trigger as expected.
All information I can think of follows.

Thanks for help.
Regards
Frank

Software:
Eclipse 4.3 Kepler Release, Build id: 20130614-0229
Google Plugin for Eclipse 4.3 3.8.0.v201410302155-rel-r43
JavaScript Debugger with Source Mapping Support 1.0.2.201501121038
Chrome Browser Version 43.0.2357.65 m

Eclipse Console SuperDevMode:
Runing CodeServer with parameters: [-noprecompile, -port, 9876, -sourceLevel, 1.7, -bindAddress, 127.0.0.1, -workDir, D:\svn\tsm\tsm-server.develop\tsm-web\target, -launcherDir, D:\svn\tsm\tsm-server.develop\tsm-web\target\webapp, -logLevel, INFO, com.glpsystems.tsm.web.TsmTest]
Super Dev Mode starting up
   workDir: D:\svn\tsm\tsm-server.develop\tsm-web\target
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Program%20Files/glassfish3122/glassfish/modules/weld-osgi-bundle.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/svn/tsm/tsm-server.develop/maven-repository/org/glassfish/main/extras/glassfish-embedded-all/3.1.2.2/glassfish-embedded-all-3.1.2.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
   Loading Java files in com.glpsystems.tsm.web.TsmTest.
   Ignored 23 units with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   Module setup completed in 14867 ms
Mai 19, 2015 6:34:44 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-8.y.z-SNAPSHOT
Mai 19, 2015 6:34:44 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started SelectChannelConnector@127.0.0.1:9876

The code server is ready at http://127.0.0.1:9876/
Code server started in 17230 ms
waited 11173 ms for code server to finish
GET /recompile/Tsm
   Job com.glpsystems.tsm.web.TsmTest_1_0
      starting job: com.glpsystems.tsm.web.TsmTest_1_0
      binding: locale=en
      Compiling module com.glpsystems.tsm.web.TsmTest
         Ignored 23 units with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
         Unification traversed 50145 fields and methods and 4066 types. 4023 are considered part of the current module and 4023 had all of their fields and methods traversed.
         Compiling 1 permutation
            Compiling permutation 0...
            Linking per-type JS with 4007 new types.
               prelink JS size = 9441519
               prelink sourcemap = 9441519 bytes and 225105 lines
               postlink JS size = 9325977
               postlink sourcemap = 9325977 bytes and 222377 lines
            Source Maps Enabled
         Compile of permutations succeeded
         Compilation succeeded -- 59,114s
      Linking into D:\svn\tsm\tsm-server.develop\tsm-web\target\com.glpsystems.tsm.web.TsmTest\compile-2\war\Tsm; Writing extras to D:\svn\tsm\tsm-server.develop\tsm-web\target\com.glpsystems.tsm.web.TsmTest\compile-2\extras\Tsm
         Link succeeded
         Linking succeeded -- 3,903s
      63,539s total -- Compile completed
GET /recompile/Tsm
   Job com.glpsystems.tsm.web.TsmTest_1_1
      starting job: com.glpsystems.tsm.web.TsmTest_1_1
      binding: locale=en
      skipped compile because no input files have changed
      0,412s total -- Compile completed
GET /sourcemaps/Tsm/A2D78521C5EDE7023410F9066F6B3607_sourcemap.json
   sent source map for module 'Tsm' in 276 ms

Eclipse Console SDBG:
[4388:2416:0519/183729:ERROR:url_pattern_set.cc(240)] Invalid url pattern: chrome://print/*
[4388:2416:0519/183729:ERROR:bluetooth_adapter_win.cc(102)] NOT IMPLEMENTED

Eclipse SDBG trace:
| Worker-34 | 2015-05-19 18:34:49.539 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Trying to load Chrome from system property chrome.location=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe |
| Worker-34 | 2015-05-19 18:34:49.543 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | => Found, location is a file, this is assumed to be the Chrome executable |
| Worker-34 | 2015-05-19 18:34:50.333 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Neuer Tab,chrome://newtab/,ws://null:53039devtools/page/31EE5239-CDF7-4905-A878-249DC7F02E17] |
| Worker-34 | 2015-05-19 18:34:50.333 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Bookmark Manager,chrome-extension://gmlllbghnfkpflemihljekbapjopfjik/_generated_background_page.html,ws://null:53039devtools/page/861DE3B5-32A8-4478-B6BD-29E15A2D8D86] |
| Worker-34 | 2015-05-19 18:34:50.333 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Choosing: [Neuer Tab,chrome://newtab/,ws://null:53039devtools/page/31EE5239-CDF7-4905-A878-249DC7F02E17] |
| Worker-34 | 2015-05-19 18:34:50.952 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Connected to WIP debug agent on host null and port 53039 |
| Thread-26 | 2015-05-19 18:34:52.045 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | Error from command id 3: {"message":"DOM agent needs to be enabled first.","code":-32000} |
| Thread-26 | 2015-05-19 18:34:53.867 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/index.html,34] |
| Thread-26 | 2015-05-19 18:34:53.873 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
| Thread-26 | 2015-05-19 18:35:06.285 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/index.html,35] |
| Thread-26 | 2015-05-19 18:35:06.288 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |

Chrome developer tools source tab:
![chrome_developer_tools_sources_view](https://cloud.githubusercontent.com/assets/2721214/7708931/bc3ea6e8-fe59-11e4-91d5-703533fc1399.png)

**Comment by branflake2267** [comment]
Is the launcher in debug mode or run mode? If its in run mode, it won't breakpoint.

**Comment by frank82178** [comment]
I start everything in debug mode: glassfish with ear application, gwt super dev mode, sdbg.
I kept the Google Developer tools closed to allow debugging through sdbg.

**Comment by ivmarkov** [comment]
Is the above trace log the complete one?
It does not look complete. I'm missing the trace entry where it should roughly say "com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/tsm_0.js,35] |

I.e. I don't see a trace entry for your main "tsm_0.js"file loaded. I'm not sure in the exact name, but if your module is called "Tsm" then it should be tsm_0.js or so. This is essentially your java code compiled to javascript by the SDM debugger.

Can you look for a similar entry?

**Comment by frank82178** [comment]
Hi,
yes, the trace was all I got.
There are a couple top level sources entries in Chrome. 
The application is deployed at localhost:9000, the codeserver runs at localhost:9876.
The file you are looking for is named "Tsm-0.js" below "(no domain)".

![chrome_developer_tools_sources_view2](https://cloud.githubusercontent.com/assets/2721214/7745989/7108b69e-ffaf-11e4-8152-318ede5ebb38.png)

**Comment by ivmarkov** [comment]
If you don't see a message for Tsm_0.js being examined for sourcemaps, there is something seriously wrong! In that case, you should not even see your app starting up and working in the Chrome browser launched by SDBG?? 

Can you also screenshot me the Eclipse Debug view once you have SDBG  more or less stopped issuing tracing messages?

**Comment by frank82178** [comment]
Oh well, it works now. Thank you for your support.

I did not call the GWT Entry Point URL directly but some html start page which in turn opend the page with the GWT application with less decoration and a fix size. This was no problem for the GWT Super Dev Mode but SDBG got confused. I guess this is not supported.

**Comment by ivmarkov** [comment]
Hm. It must be supported. We do not rely on any special tricks like URLs or suchlike. SDBG (and chromeDEVTools for that matter) receives by the browser an event for every loaded javascript file. So if your app was running (even if this was in the Chrome browser with hidden address bar/whatever), SDBG should have received a notification from the browser for your Tsm_0.js file and should have loaded the sourcemap.

Can you isolate this to an elementary test case? Like, maybe your html page and then a super-simple GWT app with a button or suchlike? Thanks in advance!

**Comment by frank82178** [comment]
There is currently no time to isolate a example but I can give you both trace logs. 
The output "Checking script for sourcemaps" seems to rely on the given URL.
Hope this helps.
---
Trace calling HTML start page URL: http://localhost:9000/tsm-web/index.html:
I left the log running until the code came over the breakpoint seen in the second trace.
---
| Worker-110 | 2015-05-21 14:12:52.369 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Bookmark Manager,chrome-extension://gmlllbghnfkpflemihljekbapjopfjik/_generated_background_page.html,ws://null:61723devtools/page/17B08C22-8E5B-4A29-9E4C-A9953F93CDBF] |
| Worker-110 | 2015-05-21 14:12:52.379 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Neuer Tab,chrome://newtab/,ws://null:61723devtools/page/6A118157-8686-4A90-8210-E90E7FE6D2DF] |
| Worker-110 | 2015-05-21 14:12:52.379 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Choosing: [Neuer Tab,chrome://newtab/,ws://null:61723devtools/page/6A118157-8686-4A90-8210-E90E7FE6D2DF] |
| Worker-110 | 2015-05-21 14:12:52.539 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Connected to WIP debug agent on host null and port 61723 |
| Thread-489 | 2015-05-21 14:12:53.447 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | Error from command id 3: {"message":"DOM agent needs to be enabled first.","code":-32000} |
| Thread-489 | 2015-05-21 14:12:54.494 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/index.html,34] |
| Thread-489 | 2015-05-21 14:12:54.494 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
| Thread-489 | 2015-05-21 14:13:10.529 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/index.html,35] |
| Thread-489 | 2015-05-21 14:13:10.539 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
---
Trace calling GWT Entry Point URL http://localhost:9000/tsm-web/Tsm.html: 
---
| Worker-112 | 2015-05-21 14:15:56.758 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Bookmark Manager,chrome-extension://gmlllbghnfkpflemihljekbapjopfjik/_generated_background_page.html,ws://null:61853devtools/page/3A440387-330A-46A2-A61A-CE320ACB0765] |
| Worker-112 | 2015-05-21 14:15:56.758 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Hotword triggering,chrome-extension://nbpagnldghgfoolbancepceaanlmhfmd/_generated_background_page.html,ws://null:61853devtools/page/740ECFF5-0AC3-4EE4-9220-881AE198310D] |
| Worker-112 | 2015-05-21 14:15:56.758 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Neuer Tab,chrome://newtab/,ws://null:61853devtools/page/CA71C754-BD19-41EF-9BF3-CB0074AF32F0] |
| Worker-112 | 2015-05-21 14:15:56.769 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found: [Google Now,chrome-extension://pafkbggdmjlpgkdkcbjmhmfcdpncadgh/_generated_background_page.html,ws://null:61853devtools/page/E7B5C934-0170-42F3-96B0-00D29187BD01] |
| Worker-112 | 2015-05-21 14:15:56.770 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Choosing: [Neuer Tab,chrome://newtab/,ws://null:61853devtools/page/CA71C754-BD19-41EF-9BF3-CB0074AF32F0] |
| Worker-112 | 2015-05-21 14:15:56.938 | com.github.sdbg.debug.core | /browser/launching | com.github.sdbg.debug.core.util.Trace | trace | 45 | Connected to WIP debug agent on host null and port 61853 |
| Thread-493 | 2015-05-21 14:15:57.561 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | Error from command id 3: {"message":"DOM agent needs to be enabled first.","code":-32000} |
| Thread-493 | 2015-05-21 14:15:59.322 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: Page.interstitialShown |
| Thread-493 | 2015-05-21 14:16:00.539 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: Page.interstitialHidden |
| Thread-493 | 2015-05-21 14:16:00.655 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/Tsm/Tsm.nocache.js,34] |
| Thread-493 | 2015-05-21 14:16:00.658 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
| Thread-493 | 2015-05-21 14:16:00.660 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: Page.frameAttached |
| Thread-493 | 2015-05-21 14:16:01.274 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9876/recompile-requester/Tsm,37] |
| Thread-493 | 2015-05-21 14:16:01.274 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
| Thread-493 | 2015-05-21 14:16:01.274 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:01.274 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:01.286 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:02.157 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9876/recompile/Tsm,38] |
| Thread-493 | 2015-05-21 14:16:02.157 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
| Thread-493 | 2015-05-21 14:16:02.157 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:02.157 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:02.167 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:02.215 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9876/Tsm/Tsm.nocache.js,39] |
| Thread-493 | 2015-05-21 14:16:02.216 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
| Thread-493 | 2015-05-21 14:16:02.217 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:02.219 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:02.220 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: Page.frameAttached |
| Thread-493 | 2015-05-21 14:16:04.966 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [Tsm-0.js,42] |
| Thread-493 | 2015-05-21 14:16:04.968 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL: http://127.0.0.1:9876/sourcemaps/Tsm/802FB641E51D90E73B298EBD95F62BA1_sourcemap.json |
| Thread-493 | 2015-05-21 14:16:05.444 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Parsing sourcemap succeeded: URLStorage[http://127.0.0.1:9876/sourcemaps/Tsm/802FB641E51D90E73B298EBD95F62BA1_sourcemap.json] |
| Thread-493 | 2015-05-21 14:16:05.494 | com.github.sdbg.debug.core | /breakpoints | com.github.sdbg.debug.core.util.Trace | trace | 45 | Breakpoint [com/glpsystems/tsm/web/client/view/TrackControllerView.java,346,-1] ==> mapped to [Tsm-0.js,85440,0] |
| Thread-493 | 2015-05-21 14:16:05.494 | com.github.sdbg.debug.core | /breakpoints | com.github.sdbg.debug.core.util.Trace | trace | 45 | Set breakpoint [Tsm-0.js,85440] |
| Thread-493 | 2015-05-21 14:16:05.514 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:05.514 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:05.524 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.inlineStyleInvalidated |
| Thread-493 | 2015-05-21 14:16:07.854 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.childNodeCountUpdated |
| Thread-493 | 2015-05-21 14:16:07.877 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.inlineStyleInvalidated |
| Thread-493 | 2015-05-21 14:16:07.898 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/Tsm.html,49] |
| Thread-493 | 2015-05-21 14:16:07.899 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |
| Thread-493 | 2015-05-21 14:16:08.093 | com.github.sdbg.debug.core | /wireProtocol | com.github.sdbg.debug.core.util.Trace | trace | 45 | unhandled notification: DOM.inlineStyleInvalidated |
| Thread-493 | 2015-05-21 14:16:11.762 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Checking script for sourcemaps: [http://localhost:9000/tsm-web/Tsm.html,76] |
| Thread-493 | 2015-05-21 14:16:11.764 | com.github.sdbg.debug.core | /sourcemaps | com.github.sdbg.debug.core.util.Trace | trace | 45 | Found sourcemap with URL:  |

**Comment by ivmarkov** [comment]
If it is not confidential, can you attach the index.html page here? I would be interested to know how it calls into the Tsm.html file... 
... because the first (the erroneous) tracelog looks as if you have somehow attached SDBG to the wrong browser tab or something... (each browser tab in Chrome is a separate chrome instance/process).

**Comment by frank82178** [comment]
I stripped it a little but here it is.

index.html:
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<script type="text/javascript">
		</script>		
	</head>
	<body>
		<div id="Container" class="template Simplicity">
			<div class="middle template">
				<div id="OuterShell" class="Simplicity">
					<header>
						<div id="HeaderBg" class="Simplicity"><div id="link-home"><a href="#" class="text-invisible"></a></div></div>
					</header>
					<div id="Content">
						<h2 class="template"></h2>
						<div id="ContentInner" class="template">
							
						</div>
						<div id="Navigation">
							<ul>
								<li class="line">
									START TSM
								</li>
								<li class="flag-gb">
									<a href="#" onclick="wopen('/tsm-web/Tsm.html?locale=en');">ENGLISH</a>
								</li>
								<li class="flag-de">
									<a href="#" onclick="wopen('/tsm-web/Tsm.html?locale=de');">GERMAN</a>
								</li>
							</ul>
						</div>
					</div> 	
				</div>
			</div>
		</div>
	</body>
</html>

**Comment by ivmarkov** [comment]
"wopen"?
Is this opening a separate browser window? If so, that explains it!
A separate browser window is a separate *tab* = separate chrome instance/process. ChromeDevTools works because you likely open it *from within this separate new tab*

**Comment by frank82178** [comment]
I edited the post to make wopen visible. See again.
I agree, there is a new window, therefore a separate process.
Yes, ChromeDevTools was opened from the new window.

**Comment by ivmarkov** [comment]
OK - closing then. As described here (https://code.google.com/p/chromium/issues/detail?id=153363), they (Chrome) plan to make these window.open()s in-process again, but they are not yet there.

**Comment by frank82178** [comment]
Thank you for helping so quickly. 
SDBG is my first choice to debug GWT code. 
I will recommend it to other projects.
Keep on going.
