### ISSUE TITLE
Is it possible to show full error strace info in console?

### ISSUE THREAD

**Issue by AlexLuya** [sdbg/sdbg#134]
Hello,
      The error messages in chrome console like this:
````javascript
Uncaught com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : Cannot read property 'ordinal_3_g$' of undefined
castFireEvent_0_g$	@	athena-0.js:149686
fireEvent_7_g$	@	athena-0.js:149710
fireEvent_2_g$	@	athena-0.js:13276
onCreateButtonClicked_4_g$	@	athena-0.js:72077
onBrowserEvent_13_g$	@	athena-0.js:72203
dispatchEventImpl_0_g$	@	athena-0.js:270336
dispatchEvent_4_g$	@	athena-0.js:270325
dispatchEvent_6_g$	@	athena-0.js:272229
apply_44_g$	@	athena-0.js:224696
entry0_0_g$	@	athena-0.js:224766
(anonymous function)	@	athena-0.js:224732

````
will be simplified one line:
````javascript
Uncaught com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : Cannot read property 'ordinal_3_g$' of undefinedcast
````

is it possible to show a full version error trace with notification "if need clickable link to source please check chrome console"?

**Comment by ivmarkov** [comment]
Hi. I'm not really sure: are you really referring to the *Chrome* console? Like, in the browser? If yes, then SDBG is not the right place for such request. Please file an issue at the Chromedevtools website:
https://developer.chrome.com/devtools
Search there, their issues repo is described on the page.

**Comment by ivmarkov** [comment]
Just to confirm: what you mean is that the full stack trace is NOT displayed in the Eclipse console / SDBG, but is displayed in the Chrome console, right?

**Comment by AlexLuya** [comment]
yes

**Comment by ivmarkov** [comment]
OK I'll look into it.

**Comment by AlexLuya** [comment]
After add this:
````xml
<inherits name='com.google.gwt.logging.Logging'/>
````
to project xml,error strace shows now.And if anyone want to know why,this thread is very worth reading:
````html
https://groups.google.com/forum/#!msg/google-web-toolkit-contributors/NvX4_6LdE5o/Kh_dl50b1nEJ
````
