### ISSUE TITLE
Installation of plugin via Plugin Update Site does not work

### ISSUE THREAD

**Issue by GryfonN** [sdbg/sdbg#137]
Eclipse version: Luna (4.4)
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Windows 7 Enterprise

![capture](https://cloud.githubusercontent.com/assets/3775835/10333170/7c3acf34-6ce2-11e5-9f1b-1a908a2bf8a5.PNG)

**Comment by ivmarkov** [comment]
How about at least providing the Eclipse version, Java runtime and OS?

**Comment by GryfonN** [comment]
sorry, you are right :+1:

**Comment by ivmarkov** [comment]
I just installed it successfully in a brand new "Eclipse for Java developers" Luna 4.4.2 (SR2) 64 bit under Windows 7 Professional.

Granted, it took quite some time of "computing requirements" before the License screen was shown, but after that it was pretty quick.

Maybe you give it a second try? Perhaps in a clean Eclipse first? Maybe the Eclipse repos are under a high load and the install is simply timing out for you (not all plugins are hosted at the SDBFG plugin website)?

**Comment by GryfonN** [comment]
Yes you are right. The problem reason was that I had many update sites in eclipse so there was some miss-calculation of dependencies, I have cleaned "Available Software Sites" section and now everything is working fine. Thanks for your accurate response and especially for you quick reaction on new issue ;)

**Comment by ivmarkov** [comment]
NP :)
Closing now
