### ISSUE TITLE
External Code Server

### ISSUE THREAD

**Issue by confile** [sdbg/sdbg#140]
My code server run on: http://192.168.178.26:9876 Is there a way to use this plugin on such a server?

Here is my configuration: 

![debug_configurations](https://cloud.githubusercontent.com/assets/64265/12074731/0f170e60-b164-11e5-9a61-175eba45fa42.jpg)
/ 

When I start debug I get: 

![error_launching_application_und_grails_-_majestella-client-chat_build_gradle_-_groovy_grails_tool_suite_-__users_mg_documents_grails_ggts3_6_4-gwt](https://cloud.githubusercontent.com/assets/64265/12074736/30289d62-b164-11e5-958e-fd93bf58a78a.jpg)

How can I fix that?

**Comment by steffimueller** [comment]
+1 I had the same problem using GWT 2.7 and 2.8--beta1.

**Comment by ivmarkov** [comment]
To both of you: 
- You do NOT have to specify to SDBG AT ALL where your code server is 
- Most important is: as long as you can access & see & recompile on refresh your app + your code server in a regular Chrome browser, SDBG will work too
- Just use the regular "Launch Chrome" debug configuration, as usual, and for URL type the URL where your app (NOT your code server) runs

Do NOT use "Connect to Chrome".

**Comment by confile** [comment]
@ivmarkov Could you please post an example of the url you mean?

**Comment by ivmarkov** [comment]
What do you type in your Chrome browser when trying to navigate to your GWT web app?

**Comment by confile** [comment]
``test.no-ip.biz:8080/test/home/client``

**Comment by ivmarkov** [comment]
That's also what you should type in the URL box of the "Launch Chrome" debug configuration as well.

**Comment by confile** [comment]
When I run the dev mode as you suggested I get the following in the console: 

```
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://test.no-ip.biz:8080/favicon.ico
```

The GWT moduled which I use for debug does not run on the index.html file I the GWT projects web-INF directory. It runs on a page on a different server. Is this a problem for debugging?
