### ISSUE TITLE
stack trace deobfuscation

### ISSUE THREAD

**Issue by nlight-jdev** [sdbg/sdbg#147]
I've seen that Chrome DevTools automatically deobfuscates the stack traces when the source maps are provided by the CodeServer.
Could this be achieved on SDBG?

Thank you!

**Comment by nlight-dev** [comment]
Not best way but enabling emulated stackMode helps a lot. Now exception stack traces have class names and line numbers.

**Comment by ivmarkov** [comment]
Sorry for the delay. I'm not really sure what you mean:
* If you are asking whether SDBG can de-obfuscate the stack-frames in the Eclipse "Debug" view - it is already doing that. Check the attached image how it looks for me.
* If you are asking whether SDBG can de-obfuscate the stack-traces that the application is dumping - I've never thought so far that this is a responsibility of SDBG. For this, we use exactly the properties you have pasted above.

![deobfuscated-stack-frames](https://cloud.githubusercontent.com/assets/2607589/18007696/cef5e96e-6bad-11e6-9d3e-7fc358636686.png)

**Comment by nlight-dev** [comment]
Hi,

It's actually when there's an exception in the GWT code, not when you put a breakpoint. Without setting any custom exception handler, the exception stack trace appears obfuscated in the console. In Chrome ypu can click the exception and see the unobfuscated one but not in SDBG.
In SDBG only by setting emulated stacktraces, the exception looks better. I guess SDBG doesn't know to translate it on demand or use the sourcemaps for this sittuation.

**Comment by nlight-dev** [comment]
any updates? thanks!

**Comment by ivmarkov** [comment]
Let's wait until GWT 2.8 is released. After that, I might try to address that, if it is not too difficult.

**Comment by keinhaar** [comment]
6 years gone. dont see any need for this.
