### ISSUE TITLE
Add interface for GWT Eclipse Plugin (V3) for shortcut launching

### ISSUE THREAD

**Issue by branflake2267** [sdbg/sdbg#149]
Could you add the interface? Or would you like me to do it? 
https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/245

**Comment by branflake2267** [comment]
Add debug interface and the new id starts with: com.gwtplugins

![screen shot 2016-10-05 at 8 26 24 am](https://cloud.githubusercontent.com/assets/1326504/19119693/6f2fe100-8ad5-11e6-8c05-97a8305e5298.png)


https://github.com/sdbg/sdbg/blob/d36f7b8fda67e59bd49d94214c8f835c0013f9b3/com.github.sdbg.integration.jdt/src/com/github/sdbg/integration/jdt/ChromeDebugLaunch.java#L6

**Comment by branflake2267** [comment]
I'm thinking the package name will cause a problem because both plugins have the same name.

**Comment by ivmarkov** [comment]
Is there a P2 repo from where I can pull the new GWT plugin (with the new package name)?

**Comment by branflake2267** [comment]
-1: http://storage.googleapis.com/gwt-eclipse-plugin/v3/release
-2: I've only renamed the packages in the newer plugins I add. The rest I've left as is so far. I'm torn on whether to rename them. The project is huge and I'm bogged down with test cases at the moment. 

http://sdbg.github.io/p2beta/

**Comment by branflake2267** [comment]
I've tested the beta deployment, .10 and it works good.

**Comment by ivmarkov** [comment]
OK, in the meantime, I've pushed it to the official repo.

**Comment by branflake2267** [comment]
Cool. I'm about to ask for folks to try things out as an EA. 

By the way if you're interested you could add a feature negation for the old plugins. This would prevent from installing on the older plugin. You're call. Here's how I did it. https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/master/features/com.gwtplugins.eclipse.suite.v3.feature/p2.inf
