### ISSUE TITLE
damaged artifact com.github.sdbg.debug.core_1.0.10.201610081555.jar

### ISSUE THREAD

**Issue by thomas-lacroix** [sdbg/sdbg#155]
OS: Windows 10 Professionnel v 1607, 64 bits

Steps to reproduce:
 - Remove old eclipse from computer: manual delete of main eclipse directory, .eclipse, .p2, and shortcuts to exec
 - Go to https://www.eclipse.org/ and download the file eclipse-inst-win64.exe (downloading from mirror or main site does not change the error)
 - Launch the Eclipse oomph installer, update and restart it through the menu.
 - Install Eclipse with default settings and launch
 - Install the SDBG eclipse plugin following http://sdbg.github.io/p2/ (or GWT Eclipse Plugin V3 following http://gwt-plugins.github.io/documentation/gwt-eclipse-plugin/Download.html)
 - The plugin doesn't install with error:
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=C__Users_XXX_eclipse_jee-latest-released_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Users\XXX\.p2\pool\plugins\com.github.sdbg.debug.core_1.0.10.201610081555.jar
 - Eclipse didn't present me with a dialogue box to accept untrusted/unsiged content as it should and usually does, the error occurs before that.
- Launch the Eclipse oomph installer again, Menu -> Bundle pools -> Analyse agent \.p2\pool. It reveals that com.github.sdbg.debug.core_1.0.10.201610081555.jar is a damaged artifact.
 - Click "repair damaged artifact" and redo the plugin installation steps. The same error prevents the install.
 - Remark1: installing the GWT Eclipse Plugin V3 without "Javascript Debugger with source map support" (aka SDBG plugin) works fine: eclipse ask to accept untrusted/unsiged content as usual and proceed with the installation.
- Remark2: I have been redoing those steps on fresh install multiple times (different mirrors, etc…) with the same problem occurring over and over.
 - Remark3: link to forum: https://groups.google.com/forum/#!topic/sdbg/xGNB3tinfds
Thomas

**Comment by branflake2267** [comment]
Do you have any peers with Windows 10 that have install issues?

**Comment by frdel-1** [comment]
Hi,
I looked around and didn't find a peer with Windows 10, the install seems to works fine on Mac and Ubuntu. I don't know if the probleme is related to the Windows 10 OS in general or to my computer in particular. Maybe the issue will go away with the next SDBG release.

**Comment by keinhaar** [comment]
works on my debian and multiple windows 10 installations at my company.
