### ISSUE TITLE
Null Pointer Exception — "this.browser" is null

### ISSUE THREAD

**Issue by yegork78** [sdbg/sdbg#175]
Hi!

Upgraded Eclipse and sdbg and now I am getting this:
"An internal error occurred during: "Launching Chrome".
Cannot invoke "com.github.sdbg.debug.core.internal.browser.IBrowser.terminateExistingBrowserProcess()" because "this.browser" is null".

Tried removing the plug-in, manually deleting all configuration from p2, workspace/.metadata, etc. Nothing helps. When I install it I get the same error.
Running macOS 13.4, having regular Chrome install.

Call stack:
```
java.lang.NullPointerException: Cannot invoke "com.github.sdbg.debug.core.internal.browser.IBrowser.terminateExistingBrowserProcess()" because "this.browser" is null
	at com.github.sdbg.debug.core.internal.browser.BrowserManager.launchBrowser(BrowserManager.java:295)
	at com.github.sdbg.debug.core.configs.ChromeLaunchConfigurationDelegate.doLaunch(ChromeLaunchConfigurationDelegate.java:98)
	at com.github.sdbg.debug.core.SDBGLaunchConfigurationDelegate.launch(SDBGLaunchConfigurationDelegate.java:51)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:806)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1040)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by keinhaar** [comment]
I expect the automatic browser detection to be very bad on OSX, because there is no active developer for this. 
Could you try to set the environment variable BROWSER_LOCATION to the full path of your chrome? and if you get that working, tell me that path, so I could then add it.

**Comment by yegork78** [comment]
Sorry, I should have mentioned that in the bug — I've read the manuals and actually tried that, before opening the bug.
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" opens Chrome in terminal and I saw that "Google Chrome.app/Contents/MacOS/Google Chrome" is already in ChromeBrowser.java, so I assumed that this is not the issue.

**Comment by keinhaar** [comment]
So does it mean, if you set BROWSER_LOCATION to "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" it still does not work? I ask, because the ChromeBrowser.java does not contain the "/Application" at the beginning.

**Comment by yegork78** [comment]
Hi!
I didn't try to debug, so I thought that "/Application" was added automatically somehow.
Yes, the BROWSER_LOCATION environment variable is set correctly; running "$BROWSER_LOCATION" from the terminal opens Chrome normally, still within eclipse I get the same exception.

**Comment by dfreismuth** [comment]
had the same problem, env var BROWSER_LOCATION only worked in bash, not in other shells (I am aware of the different syntaxes of setting an env variable), try the following:
env BROWSER_LOCATION="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" bash -c /Applications/Eclipse.app/Contents/MacOS/eclipse

**Comment by keinhaar** [comment]
@dfreismuth  @yegork78 
Could someone of you check with the 2.2 beta, if the issue has been fixed?

**Comment by yegork78** [comment]
@keinhaar Yes, I can confirm that on my machine the 2.2 beta works, THANKS!
(standard default Chrome install on macOS 13.5.1)

**Comment by keinhaar** [comment]
Thanks for feedback.
