### ISSUE TITLE
Support for Internet Explorer

### ISSUE THREAD

**Issue by ivmarkov** [sdbg/sdbg#21]
This is not impossible, but quite some work, as IE is of course not using the WIP protocol. (I'm actually not even sure what it is using.) Probably not so important, as if we are lucky, this (http://remotedebug.org/) may take off in the meantime, and then IE support will come for free.

**Comment by ivmarkov** [comment]
It seems the world is slowly uniting around the Chrome debugging protocol, Microsoft being no exception:
https://compatibility.remotedebug.org/

 They now support this:
https://github.com/Microsoft/edge-diagnostics-adapter

so in theory if one runs this adapter, SDBG should be able to debug Edge. To be checked...

**Comment by keinhaar** [comment]
Internet Explorer is dead! 
But the new Chromium based Edge works if you set 
```
-Dchrome.location=C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe
