### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by ivmarkov** [sdbg/sdbg#22]
This is not impossible, but quite some work, as Firefox's JSD2 seems quite a bit different from WIP. If we are lucky, this (http://remotedebug.org/) may take off in the meantime, and then Firefox support will come for free.

**Comment by jonl-percsolutions-com** [comment]
It appears there has been movement on the firefox bridge:

https://github.com/auchenberg/remotedebug-firefox-bridge

**Comment by ivmarkov** [comment]
How exactly did you come to that conclusion? :)
Latest commit is 5 months ago - and it seems to be a pull request for a simple rename.
All the rest seems to be one to two years old...

**Comment by jonl-percsolutions-com** [comment]
My comment was more informational for anyone who came across this request and wondering what the status of it the firefox implementation of remotedebug, or even that there was one, could know about that repo and possibly commit to it if they have time instead of digging around themselves.

**Comment by keinhaar** [comment]
Firefox starts if you set 
```
-Dchrome.location=C:/Program Files/Mozilla Firefox/firefox.exe
```
to eclipse.ini, and add the browser parameter -debug in Launch Configuration.
But still debugger does not connect...

**Comment by keinhaar** [comment]
Firefox support is in development. To see the current state, look at my personal branch. 
https://github.com/keinhaar/sdbg/tree/firefox

**Comment by keinhaar** [comment]
Firefox support is now in the current beta version.
It needs a little tweak for GWT Projects, but the it will work like the Chrome version.
