### ISSUE TITLE
View, displaying all javascript files and source files loaded in the browser

### ISSUE THREAD

**Issue by ivmarkov** [sdbg/sdbg#23]
IMO not so important for an IDE plugin as your source files are anyways already lying around in your Eclipse projects, but the others (ChromeDevTools & IDEA) are having this option, so probably we should have it as well. Also, the WebkitRemoteScriptSourceContainer allows you to have the remote JavaScript/other source files automatically opened in Eclipse when clicking on a relevant stackframe (this happens when these files are otherwise not found in the Eclipse workspace of course, or else the corresponding files from the workspace will open which will allow you to edit these files as well if you wish). However, these remote files cannot be "listed" or "browsed", as the Eclipse notion of ISourceContainer does not have the notion of "enumerating" source files.

JSDT and the old Chromedevtools-Java Eclipse debuggers create an autogenerated Eclipse project and then place the remote source files in there. This is a bit ugly as it pollutes the workspace of the user. Also it makes the "Open Resource" and "Open Type" dialogs annoying to use, as you never know whether you are opening the original file, or its remote mirror existing in the browser...

**Comment by keinhaar** [comment]
I see no need for this, and nobody ever worked on this.
