### ISSUE TITLE
Merging with Google Plugin for Eclipse

### ISSUE THREAD

**Issue by joelhandwell** [sdbg/sdbg#99]
It would be helpful merging this with GPE. I'm aware GPE development is currently able to do in Google internally, but [they plan to move repo to github and make it able to build outside of Google](https://groups.google.com/forum/#!searchin/google-plugin-eclipse/github/google-plugin-eclipse/2dFMIdSsBBk/2YKhou-o_XEJ).

**Comment by ltearno** [comment]
+1 !

Le Mon Jan 12 2015 at 21:13:33, Joel Handwell <notifications@github.com> a
écrit :

**Comment by confile** [comment]
+1

**Comment by branflake2267** [comment]
GPE is in process of getting open sourced, although its taking longer than expected.

**Comment by ivmarkov** [comment]
Yes, a tight(er) integration between GPE and SDBG is necessary. 
* E.g. launching GPE's SuperDevMode should ideally simultaneously launch an SDBG Chrome debug session as well
* E.g. downloading GPE should be enough as it should ideally depend on (and bring-in during installation) SDBG as well.

Whether the two efforts should be merged in a single GitHub repo is another story - depends on who is volunteering to maintain GPE, how big the codebase is etc. etc. Let's have the GPE open-sourced first and then we'll see what is the best way to proceed with integrating the two efforts.

Let's keep this issue as a place-holder for future integration discussions.

**Comment by branflake2267** [comment]
I think a faster integration story might be getting this into the market and/or possibly bundling the feature in a the install rather than having to actually merge the code. My opinion would be to figure out how to deliver the installable with the two. The GPE project is huge and merging the code could tangle it, where looking at it like a transitive dependency might be more effective. 

What would it take to get this into the market?

**Comment by branflake2267** [comment]
I'm currently working on a prototype, a WTP GWT Facet for GPE and nearly have all the parts working together. Anyway, more on the specifics later. The goal is to start the WTP runtime server, this would start the SDM code server and then this could start the debugger. I've finished a launcher for just the CodeServer entrypoint. To the point, the goal is to provide an extension point so to trigger the debugger either on gpe side or sdbg. I've been working on this vigorously the last several weeks and hoping to have a preview at the conference which should bring together a more fluid experience. The current launchers could add an extension point if there isn't one already to instantiate the sdbg javascript debugger too. (GPE is getting open sourced, its just taking longer than expected).

**Comment by ltearno** [comment]
Do you think about getting GAE out of GPE ? That could reduce the GPE
codebase

Thanks
Arnaud

**Comment by branflake2267** [comment]
It's come up in discussions. Keep in mind separating the two will take a bunch of work. I lean more on keeping them together because think there is more benefit in the symbiotic relationship at the moment. I suspect open sourcing it will solve most of the frustrations. But thats just my take at the moment.

**Comment by ivmarkov** [comment]
In general, I agree with you that it is too early about considering code merging. Given the Eclipse plugins story, extension points etc. I think we can do well by integrating the two even if they continue to live as separate code-bases, at least for now.

Regarding "a faster integration story might be getting this into the market"
* Could you clarify what you mean by "market"? Eclipse Market? How would publishing SDBG on the market ease the integration story?

Regarding "and/or possibly bundling the feature in a the install"
* Bundling is one option. Isn't another option to just express an option dependency in GPE on SDBG? This way, when GPE is being installed, optionally, SDBG will be downloaded and installed as well?

**Comment by ivmarkov** [comment]
To Brian: How does the extension point in GPE for launching SDBG look like? What shall I look at?

**Comment by branflake2267** [comment]
Marketplace: I was thinking it would make for an easy install if not bundled. Although copying the update site is simple too. GPE market place addition is out of date too. I guess I could say I've liked the install instructions using the marketplace. 
![screen shot 2015-01-13 at 9 31 08 am](https://cloud.githubusercontent.com/assets/1326504/5725350/eff7677e-9b06-11e4-8ab0-f6acc2f09cd5.png)

Bundling: I'm not as familiar enough with transitive options yet. I like the option of stating it in the plugin. That sounds doable sooner than later.

**Comment by joelhandwell** [comment]
I think it's already achieved. So closing this issue. If anything new please comment or reopen. Thanks.
